In [3]:
import torch
torch.__version__

'2.7.1+cu128'

In [24]:
# scalar
scalar = torch.tensor(7)
scalar.ndim, scalar.shape, scalar.item()

(0, torch.Size([]), 7)

In [28]:
# Vector 
vector = torch.tensor([7, 7])
vector
vector.ndim, vector.shape

(1, torch.Size([2]))

In [31]:
# Matrix 
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [34]:
# Random tensors
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.1098, 0.2215, 0.1845, 0.2647],
         [0.3617, 0.9194, 0.1798, 0.7608],
         [0.9724, 0.6577, 0.8902, 0.6948]]),
 torch.float32)

In [37]:
# Zeros 
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [38]:
# Ones 
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [42]:
# Creating a range and tensors like 
# torch.arange(start, end, step)
even_nums = torch.arange(start=0, end=10 , step=2)
even_nums

tensor([0, 2, 4, 6, 8])

In [43]:
"""
Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.
"""

five_zeros = torch.zeros_like(input=even_nums)
five_zeros

tensor([0, 0, 0, 0, 0])

In [44]:
# Tensor Datatypes

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # defaults to None, which is torch.float32 or whatever datatyped is passed
                              device=None, # default to None, which usess the fault tensor type
                              requires_grad=False) # if True, operations performed on the tensor are recoreded
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

<h1>Tensor Operations</h1>

In [46]:
tensor = torch.tensor([1, 2, 3])
tensor + 10 

tensor([11, 12, 13])

In [48]:
tensor * 10 # more common
# or 
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [49]:
tensor - 10

tensor([-9, -8, -7])

In [50]:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [57]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [58]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [52]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

* You can do matrix multiplication by hand but it's not recommended.
* The in-built torch.matmul() method is faster.

In [56]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0 
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 287 μs


tensor(14)

In [59]:
%%time 
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 58.4 μs


tensor(14)

# One of the most common errors in deep learning (shape errors)
* Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [63]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]], dtype=torch.float32)
tensor_B = torch.tensor([[7, 10],
                       [8, 11],
                       [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) #(causing error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [70]:
# We can fix that with Transpose 
print(tensor_A.shape, tensor_B.shape)
print(tensor_A.shape, tensor_B.T.shape)
tensor_A @ tensor_B.T


torch.Size([3, 2]) torch.Size([3, 2])
torch.Size([3, 2]) torch.Size([2, 3])


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [72]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])